create table if not exists scores (
  id bigint generated by default as identity primary key,
  name text not null,
  wave integer not null,
  lives integer,
  gold integer,
  towers integer,
  created_at timestamp with time zone default now()
);

create index if not exists scores_wave_idx on scores(wave desc);
